config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post '/graphql',  to: 'graphql#execute'

  namespace :api do
    namespace :v1 do
      resources :users
      resources :notes
    end
  end

  post 'refresh',   controller: :refresh, action: :create
  post 'signin',    controller: :signin,  action: :create
  delete 'signin',  controller: :signin,  action: :destroy
  post 'signup',    controller: :signup,  action: :create

  root 'notes#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  scope :active,    -> { where(is_active: true) }
  scope :pending,   -> { where(is_active: false) }

  def owned_by?(user_to_verify)
    user.present? && user == user_to_verify
  end

  # In retrospect, the column should be called active not is_active so this method would not be needed
  def active?
    is_active
  end

  def approve
    self.is_active = true
    self.save
  end
end

app/controllers/api/v1/notes_controller.rb
module Api
  module V1
    class NotesController < ApplicationController
      # Between these two methods,all actions are blacklisted unless specifically whitelisted
      #skip_before_action :authorised,             only: [:index, :show]
      before_action :authorised_for_note_actions, except: [:index, :show, :new, :create, :pending, :approve]
      #before_action :authorized_access_request!, except: [:index, :show, :new, :create, :pending, :approve]
      
      before_action :authorised_to_view_pending_note, only: [:show]
      before_action :authorised_for_moderation,       only: [:pending, :approve]

      def index
        @notes = Note.by_admin.active.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
        render json: @notes
      end

      def show
        @note = Note.find(params[:id])
        render json: @note
      end

      def new
        @note = Note.new
        render json: @note
      end

      def create
        @note = Note.new(note_params)
        @note.user = current_user
        if @note.save
          # respond_to do |format|
          #   format.js {
          #     flash[:alert] = "Your note was successfully created, and is pending moderation"
          #     render js: "window.location = '#{note_path(@note)}'"
          #   }
          # end
        else
          # respond_to do |format|
          #   format.js
          # end
        end
      end

      def edit
      end

      def update
        if @note.update(note_params)
          render json: @note, status: :created, location: @note
          # respond_to do |format|
          #   format.js {
          #     flash[:success] = "Note was updated"
          #     render js: "window.location = '#{note_path(@note)}'"
          #   }
          # end
        else
          render json: @note.errors, status: :unprocessable_entity
          # respond_to do |format|
          #   format.js
          # end
        end
      end

      def destroy
        @note.destroy
        flash[:success] = "Note was deleted"
        redirect_to root_path
      end

      def pending
        @notes = Note.pending.paginate(page: params[:page], per_page: 5)
        render json: @notes
      end

      def approve
        @note = Note.find(params[:note_id])
        if @note.approve
          render json: @note, status: :updated, location: @note
          #flash[:success] = "Note was approved"
        else
          render json: @note.errors, status: :unprocessable_entity
          #flash[:danger] = "Something went wrong approving this note"
        end
        #redirect_to pending_notes_path
      end

      private

      def note_params
        params.require(:note).permit(:title, :description)
      end

      def authorised_to_view_pending_note
        @note = Note.find(params[:id])
        # This is worthy of a refactor
        unless @note.active? || logged_in_as_admin? || (logged_in? && @note.owned_by?(current_user))
          flash[:danger] = "You are not authorised to perform that action"
          redirect_to root_path
        end
      end

      # Applies to edit, update & destroy
      def authorised_for_note_actions
        @note = Note.find(params[:id])
        unless @note.owned_by?(current_user) || logged_in_as_admin?
          flash[:danger] = "You are not authorised to perform that action"
          redirect_to root_path
        end
      end

      def authorised_for_moderation
        unless logged_in_as_admin?
          flash[:danger] = "You are not authorised to perform that action"
          redirect_to root_path
        end
      end
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def created_by_name(note)
    if note.user.present?
      note.user.username
    else
      '[Removed user]'
    end
  end
end

app/views/notes/_controls.html.erb
<% if note.owned_by?(current_user) || logged_in_as_admin? %>
  <div class="note-actions">
    <% if !note.active? && logged_in_as_admin? %>
      <%= link_to "Approve", note_approve_path(note), method: :put, class: "btn btn-xs btn-success" %>
    <% end %>
    <%= link_to "Edit", edit_note_path(note), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", note_path(note), method: :delete, data: { confirm: "Are you sure you want to delete this note?"}, class: "btn btn-xs btn-danger" %>
  </div>
<% end %>

app/views/notes/_form.html.erb
<%= render partial: 'shared/errors', locals: { obj: @note } %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@note, html: {class: "form-horizontal", role: "form"}, remote: true) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Note description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-success btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/_note.html.erb
<% obj.each do |note| %>
  <ul class="note">
    <div class="row">
      <div class="well col-md-8 col-md-offset-2">
        <li class="note-title">
          <%= link_to note.title, note_path(note) %>
        </li>
        <div class="note-body">
          <%= truncate(note.description, length: 100) %>
          <div class="note-meta-details">
            <small>
              Created by: <%= created_by_name(note) %>,
              <%= time_ago_in_words(note.created_at) %> ago, last updated: <%= time_ago_in_words(note.updated_at) %> ago
            </small>
          </div>
          <%= render partial: 'controls', locals: { note: note } %>
        </div>
      </div>
    </div>
  </ul>
<% end %>

app/views/notes/create.js.erb
$('#form_container').html("<%= j render(partial: 'form', locals: { obj: @note }) %>");

app/views/notes/edit.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>Edit Note</h1>
</div>

<div id="form_container">
  <%= render partial: 'form' %>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= link_to 'Back', root_path, class: "btn btn-primary btn-large" %>
    <%= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure you want to delete this note?"}, class: "btn btn-danger btn-large" %>
  </div>
</div>

app/views/notes/index.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>Notes application index page</h1>
</div>

<%= render partial: 'note', locals: { obj: @notes } %>

<div align="center">
  <%= will_paginate @notes %>
</div>

app/views/notes/new.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>Create a new note</h1>
</div>

<div id="form_container">
  <%= render partial: 'form' %>
</div>

<div class="col-xs-8 col-xs-offset-2">
  <%= link_to 'Back', root_path, class: "btn btn-primary btn-large" %>
</div>   

app/views/notes/pending.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>Notes pending approval</h1>
</div>

<%= render partial: 'note', locals: { obj: @notes } %>

<div align="center">
  <%= will_paginate @notes %>
</div>

app/views/notes/show.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>
    <% unless @note.active? %>
      <i title="User is an admin" class="fa fa-hourglass-half"></i>
    <% end %>
    Title: <%= @note.title %>
  </h1>
</div>

<div class="well col-xs-8 col-xs-offset-2">
  <h4>Description:</h4>
  <hr>
  <%= simple_format(@note.description) %>
  <%= render partial: 'controls', locals: { note: @note } %>
</div>

<div class="col-xs-8 col-xs-offset-2">
  <%= link_to 'Back', root_path, class: "btn btn-xs btn-success" %>
</div>

app/views/notes/update.js.erb
$('#form_container').html("<%= j render(partial: 'form', locals: { obj: @note }) %>");