config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post '/graphql',  to: 'graphql#execute'

  namespace :api do
    namespace :v1 do
      resources :users
      resources :notes
    end
  end

  post 'refresh',   controller: :refresh, action: :create
  post 'signin',    controller: :signin,  action: :create
  delete 'signin',  controller: :signin,  action: :destroy
  post 'signup',    controller: :signup,  action: :create

  root 'notes#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Notes App", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to "Create note", new_note_path %>
          </li>
        <% end %>
        <% if logged_in_as_admin? %>
          <li>
            <%= link_to "Pending notes", pending_notes_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in_as_admin? %>
          <li>
            <%= link_to "New user", new_user_path %>
          </li>
        <% end %>
        <% if logged_in? %>
          <li>
            <%= link_to "My profile", user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Edit my profile", edit_user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign up", signup_path %>
          </li>
          <li>
            <%= link_to "Log in", login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'shared/messages' %>
    <%= yield %>
  </body>
</html>